name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: build the app
      run: npm run build

    - name: debug build folder
      run: ls -la

    - name: Run tests
      run: echo "npm run test" # npm run test, funktioniert bei mir nicht Missing script aber wäre richtig

    - name: Lint code
      run: npm run lint